baseURL = 'https://mariasaavedra.github.io/'
languageCode = 'en-us'
title = 'M. Saavedra'
copyright = "© Maria Saavedra"
theme = "github.com/athul/archie"
paginate=3 # articles per page

[params]
    subtitle = "Sporadic thoughts and insights"
	mode="toggle" # color-mode → light,dark,toggle or auto
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support


# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mariasaavedra"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/Maria_Saavedra"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/msaav/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Articles"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4